---
extends: default

ignore: |
  changelogs

rules:
  # 80 chars should be enough, but don't fail if a line is longer
  line-length: disable
  colons:
    max-spaces-before: 0
    max-spaces-after: -1
  document-end: {present: true}
  indentation:
    level: error
    indent-sequences: consistent
  truthy:
    level: error
    allowed-values:
    - 'True'
    - 'False'
    - 'true'
    - 'false'
    - 'on'
...
