---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  deployment_type: awx
  replicas: 1
  admin_user: admin
  admin_password_secret: awx-admin-password
  service_type: nodeport
#  broadcastWebsocketSecret: password
  ingress_type: Ingress
  create_preload_data: true
  development_mode: true
  # image: ansible/awx:19.0.0 # replace this with desired image
  # these requirements are best guess, may change in the future.
  web_resource_requirements:
    requests:
      cpu: 250m
    limits:
      cpu: 300m
  task_resource_requirements:
    requests:
      cpu: 250m
    limits:
      cpu: 300m
...
