---
name: Run Tower Configuration

on: [push, pull_request]

jobs:
  Integration-test:
    name: Deploy configuratrion to Tower
    runs-on: ubuntu-latest
    steps:
      - name: "Install Galaxy dependencies"
        run: ansible-galaxy collection install -r collections/requirements.yml

      - name: "Configure Prod"
        run: ansible-playbook configure_controller.yml -e controller_hostname=${{ secrets.CONTROLLER_HOSTNAME }} -e controller_username=${{ secrets.CONTROLLER_USERNAME }} -e controller_password=${{ secrets.CONTROLLER_PASSWORD }} -e env_type="prod"

      - name: "Configure Lab"
        run: ansible-playbook configure_controller.yml -e controller_hostname=${{ secrets.CONTROLLER_HOSTNAME }} -e controller_username=${{ secrets.CONTROLLER_USERNAME }} -e controller_password=${{ secrets.CONTROLLER_PASSWORD }} -e env_type="lab"
...
