name: Ansible Lint # feel free to pick your own name
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v2
      - name: See what is where
        run: |
          ls 
      - name: Run ansible-lint
        # replace `main` with any valid ref, or tags like `v6`
        uses: sean-m-sullivan/ansible-lint-action@main
        with:
          path: ""
          config_path: ".github/workflow-config/.ansiblelint.yml"
